[2024-08-12 17:04:17,106: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-12 17:04:17,110: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-12 17:04:17,111: INFO: common: created directory at: artifacts]
[2024-08-12 17:04:17,111: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-12 17:04:20,139: INFO: 1170291011: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 11616915
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "adf745abc03891fe493c3be264ec012691fe3fa21d861f35a27edbe6d86a76b1"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 0AA8:2F72DE:1B32609:1CA5433:66BA2470
Accept-Ranges: bytes
Date: Mon, 12 Aug 2024 15:04:17 GMT
Via: 1.1 varnish
X-Served-By: cache-fra-eddf8230152-FRA
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1723475057.696096,VS0,VE744
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 08c796f78c20a6e87056d8f916e92ddfe0300044
Expires: Mon, 12 Aug 2024 15:09:17 GMT
Source-Age: 1

]
[2024-08-12 17:28:48,353: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-08-12 17:28:48,356: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-12 17:28:48,357: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-12 17:28:48,357: INFO: common: created directory at: artifacts]
[2024-08-12 17:28:48,357: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-12 17:28:48,358: INFO: data_ingestion: File already exists of size: ~ 11345 KB]
[2024-08-12 17:28:48,695: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-08-12 17:28:48,695: INFO: main: *******************]
[2024-08-12 17:28:48,695: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-08-12 17:28:48,698: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-12 17:28:48,698: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-12 17:28:48,699: INFO: common: created directory at: artifacts]
[2024-08-12 17:28:48,699: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-08-12 17:28:48,700: ERROR: main: "'ConfigBox' object has no attribute 'image_size'"]
Traceback (most recent call last):
  File "box\box.py", line 503, in box.box.Box.__getitem__
KeyError: 'IMAGE_SIZE'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\box.py", line 536, in box.box.Box.__getattr__
  File "box\box.py", line 524, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'IMAGE_SIZE'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 538, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'IMAGE_SIZE'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\config_box.py", line 28, in box.config_box.ConfigBox.__getattr__
  File "box\box.py", line 552, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'IMAGE_SIZE'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 503, in box.box.Box.__getitem__
KeyError: 'image_size'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\box.py", line 536, in box.box.Box.__getattr__
  File "box\box.py", line 524, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'image_size'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 538, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'image_size'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 26, in <module>
    prepare_base_model.main()
  File "c:\shri_code\chicken_disease_classification\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 14, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
  File "c:\shri_code\chicken_disease_classification\src\cnnClassifier\config\configuration.py", line 52, in get_prepare_base_model_config
    params_image_size=self.params.IMAGE_SIZE,
  File "box\config_box.py", line 30, in box.config_box.ConfigBox.__getattr__
  File "box\box.py", line 552, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'image_size'"
[2024-08-12 17:30:58,548: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-12 17:30:58,550: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-12 17:30:58,551: INFO: common: created directory at: artifacts]
[2024-08-12 17:30:58,552: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-08-13 18:57:55,405: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-13 18:57:55,409: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-13 18:57:55,411: INFO: common: created directory at: artifacts]
[2024-08-13 18:57:55,411: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-08-13 19:03:56,800: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-13 19:03:56,804: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-13 19:03:56,805: INFO: common: created directory at: artifacts]
[2024-08-13 19:03:56,806: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-08-13 19:04:02,038: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-13 19:06:59,516: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-08-13 19:06:59,519: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-13 19:06:59,521: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-13 19:06:59,521: INFO: common: created directory at: artifacts]
[2024-08-13 19:06:59,521: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-13 19:06:59,522: INFO: data_ingestion: File already exists of size: ~ 11345 KB]
[2024-08-13 19:07:00,036: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-08-13 19:07:00,036: INFO: main: *******************]
[2024-08-13 19:07:00,036: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-08-13 19:07:00,039: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-13 19:07:00,040: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-13 19:07:00,042: INFO: common: created directory at: artifacts]
[2024-08-13 19:07:00,042: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-08-13 19:07:00,431: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-13 19:07:00,637: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
